version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install linter
          command: pip install flake8
      - run:
          name: Run flake8
          command: flake8 .

  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest -v

    docker-build:
      docker:
        - image: cimg/base:stable   # Base image with Docker installed
      steps:
        - setup_remote_docker       # removed "version"
        - checkout
        - run:
            name: Build Docker image
            command: docker build -t myapp:latest .
        - run:
            name: Save Docker image as artifact
            command: docker save myapp:latest | gzip > myapp.tar.gz
        - persist_to_workspace:
            root: .
            paths:
              - myapp.tar.gz

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - docker-build:
          requires:
            - build
